# Generated by Django 5.2.2 on 2025-06-18 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='processing', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_data', models.JSONField(null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
