# Generated by Django 5.2.3 on 2025-01-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_api', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrule',
            name='reference_field',
            field=models.CharField(blank=True, help_text="Field to compare against (e.g., 'items' for line items)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='calculation_type',
            field=models.CharField(blank=True, choices=[('sum', 'Sum'), ('average', 'Average'), ('count', 'Count'), ('min', 'Minimum'), ('max', 'Maximum')], help_text='Type of calculation for cross-reference validation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acceptable difference for numerical comparisons', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='Whether this rule was automatically created from patterns'),
        ),
        migrations.AlterField(
            model_name='validationrule',
            name='rule_type',
            field=models.CharField(choices=[('regex', 'Regular Expression'), ('data_type', 'Data Type'), ('required', 'Required Field'), ('range', 'Value Range'), ('enum', 'Enumeration'), ('cross_reference', 'Cross-Reference Validation'), ('calculation', 'Calculation Validation')], max_length=20),
        ),
    ] 