# Generated by Django 4.2.7 on 2025-07-12 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents_api', '0006_add_cross_reference_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('integration_type', models.CharField(choices=[('sap_erp', 'SAP ERP'), ('salesforce', 'Salesforce'), ('ms_dynamics', 'Microsoft Dynamics'), ('quickbooks', 'QuickBooks'), ('custom_api', 'Custom API'), ('webhook', 'Webhook'), ('database', 'Database')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('endpoint_url', models.URLField(blank=True, max_length=500, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('config_data', models.JSONField(default=dict, help_text='Additional configuration parameters')),
                ('supported_document_types', models.JSONField(default=list, help_text='List of supported document types')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('testing', 'Testing')], default='inactive', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.PositiveIntegerField(default=60, help_text='Sync frequency in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='workflow_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount threshold that requires approval', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='auto_approve_below_threshold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approval_group',
            field=models.CharField(blank=True, help_text='Group of users who can approve', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='condition_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('eq', 'Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('contains', 'Contains')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='condition_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='integration_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='integration_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='requires_all_approvers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('processing', 'Processing'), ('approval', 'Approval'), ('integration', 'Integration'), ('notification', 'Notification')], default='processing', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_data', models.JSONField(default=dict, help_text='Data collected during workflow execution')),
                ('error_log', models.TextField(blank=True, null=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents_api.workflowstep')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to='documents_api.document')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='documents_api.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeSyncStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('document_status', 'Document Status'), ('approval_status', 'Approval Status'), ('integration_data', 'Integration Data'), ('workflow_progress', 'Workflow Progress')], max_length=20)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('next_sync', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_status', models.CharField(blank=True, max_length=100, null=True)),
                ('external_data', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_statuses', to='documents_api.document')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_statuses', to='documents_api.integrationconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('sync', 'Synchronization'), ('send', 'Data Send'), ('receive', 'Data Receive'), ('error', 'Error'), ('test', 'Test Connection')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('partial', 'Partial')], max_length=20)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('external_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='documents_api.document')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents_api.integrationconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('delegation_reason', models.TextField(blank=True, null=True)),
                ('approval_level', models.PositiveIntegerField(default=1)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_approvals', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents_api.document')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents_api.workflowstep')),
            ],
        ),
    ]
