# Generated by Django 4.2.7 on 2025-07-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents_api', '0007_integrationconfiguration_document_current_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentapproval',
            name='workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents_api.workflowstep'),
        ),
    ]
